### ISSUE TITLE
Default with choose 

### ISSUE THREAD

**Issue by maurobender** [JEG2/highline#191]
It would be nice to be able to set a default option for the menus, something like:
```ruby
choose do |menu|
    menu.prompt = 'What item do you prefer?'
    menu.choices :first, :second
    menu.default = :first
end
```

The output could be, for :one_line layouts:
```sh
What item do you prefer? ([first], second) _
```
and for lists:
```sh
1. first
2. second
What item do you prefer? [1. first] _
```

**Comment by abinoam** [comment]
Hi @maurobender,

Thank you for you suggestion.
I'll let it open, so we can keep it on sight. So we can work on it when having some time.
I will not promise I can touch it soon, because I'm in a really busy schedule these days.
If you (or anyone interested) want, you can try to open a pull request with the code of this feature.
We will be glad to help you through the process.
Thank you again for the suggestion (and for the other issue reporting the bug).

**Comment by abinoam** [comment]
Hi @maurobender,

We're closing this thanks @fredrb.

See #203 for details.
