### ISSUE TITLE
"NameError: undefined local variable or method 'key'" when using `gather` as hash

### ISSUE THREAD

**Issue by gruz0** [JEG2/highline#199]
I've got this error `NameError: undefined local variable or method `key' for #<HighLine:0x000000031a5d58>` when I try to use code like this:
```
value = cli.ask("<%= key %>") do |q|
  q.echo         = '*'
  q.verify_match = true
  q.gather       = { 'Enter a password:' => '', 'Please type it again for verification:' => '' }
end
```

Solution: use @key in #ask

**Comment by abinoam** [comment]
Hi @gruz0,

Thank you for your attention on this.
Could you confirm what version are you running the examples at?
Could you please try something like 
```ruby
puts HighLine::VERSION
```
Because this was changed in 2.0.0-develop.1
And I think you're probably running the stable version 1.7.x
And, at this version, this files reads like your suggestion.
Look at it at: https://github.com/JEG2/highline/blob/1-7-stable/examples/repeat_entry.rb#L14

If you want to experiment with our pre release version that has some changes in the api you could do it by doing as follows:

```
gem install highline --pre
```

Or by using this at your Gemfile

```
gem 'highline', '~> 2.0.pre'
``` 

Please let me know if you need any futher help! 👍

**Comment by gruz0** [comment]
Hi, @abinoam!

I use 1.7.8. :-)

**Comment by abinoam** [comment]
The 1-7-stable branch is here.
https://github.com/JEG2/highline/blob/1-7-stable/examples/repeat_entry.rb
And the docs are already correct for that version.

I'll close the issue and PR. You can reopen it at anytime if you think it's necessary.
Thank you @gruz0 for interest in HighLine.
