### ISSUE TITLE
undefined method 'default_instance'

### ISSUE THREAD

**Issue by lebogan** [JEG2/highline#223]
I get this message when I try to run the page_and_wrap.rb example:
```
NoMethodError: undefined method 'default_instance' for HighLine:Class
```
I am using highline 1.7.8, bundler 1.16.0, and ruby 2.3.3.

Thanks for any insight.

**Comment by lebogan** [comment]
Update:
I downloaded and built version 2.0.0.pre.develop.14 and ran the example again. It works with this version.
What am I missing?

**Comment by abinoam** [comment]
Hi @lebogan, 

We're not actively updating 1-7-stable branch.
So I strongly encourage to experiment and migrate to 2-0 branch.
But I added this to 1-7-stable because I think is important for avoiding confusion.
See PR #224 

Now (at 1-7 and 2-0) you may run

`bundle exec ruby examples/page_and_wrap.rb`

and bundle will take care of correctly handling dependencies and load path.

Could please give me some feedback if it worked for you now?

**Comment by lebogan** [comment]
Thank you. That worked.
