### ISSUE TITLE
highline 1.6.9 hangs indefinitely with JRuby

### ISSUE THREAD

**Issue by graaff** [JEG2/highline#31]
With jruby 1.5.6 (ruby 1.8.7 patchlevel 249) (2012-01-08 6586) (OpenJDK 64-Bit Server VM 1.6.0_22) [amd64-java] tests hang indefinitely. I've tested both with and without your patch for my ruby 1.8 bug. It shows two dots when running its tests and then hangs. I realize that our jruby is old but we can't currently upgrade since 1.6 versions don't run properly on our system.

**Comment by abinoam** [comment]
It seems io/console is available on recent vesions of JRuby and it works pretty similar to how it works on MRI.
So I'm trying to unify the approaches for MRI and JRuby on this PR #149

The test suit just 'skips' the readline cases when at jruby. Because I couldn't figured out a way to test them. (If you know how to do it, please tell me so).
So the tests will not hang indefinitely (waiting for console user input).

But you can be sure that it is working fine by using ```rake acceptance```
This rake task will show you some use cases of HighLine and ask you if it's working or not.

By skipping this particular readline case on test suit we have all tests passing in travis https://travis-ci.org/abinoam/highline (jruby-19mode)

Could you people interested in (and familiar to) JRuby support give some feedback about the PR #149 ?

Hooking anyone that has commented in any HighLine JRuby issue: @rsutphin @mnzaki @graaff @Flameeyes @tomdz @andlaz @jeremyd @rsutphin @kgx @thinkgareth @presidentbeef @JEG2 @alexch @stomar @BanzaiMan @ai @celeduc @oreoshake @antond @jcoyne @keshavkuruva @cfbrobak  @astounding

**Comment by abinoam** [comment]
... and I think PR #149 also closes issue #51

**Comment by abinoam** [comment]
After PR #149 I think most of JRuby problems are gone. Closing.
